### PR TITLE
Fix nofriends on 23/11/09 Steam Beta break

### PR DESCRIPTION
**Pull request by AkazaRenn**
https://github.com/suchmememanyskill/Steam-Deck-Themes/issues/47

I tested it safe for stable but please test again on your side.

### CODE REVIEW

**Comment by suchmememanyskill** [comment]
I have a few issues with this:
- Please apply it to shared.css, so that it also works properly when no-friends is toggled off
- The height of the games is not the same as it was before. This is the part i was talking about being unfixable without breaking stable

I think the best release strategy for this is to wait until the new ui is pushed to stable

**Comment by AkazaRenn** [comment]
> I have a few issues with this:
> 
> * Please apply it to shared.css, so that it also works properly when no-friends is toggled off
> * The height of the games is not the same as it was before. This is the part i was talking about being unfixable without breaking stable
> 
> I think the best release strategy for this is to wait until the new ui is pushed to stable

I'm not sure about the new `100vh - 50px - 14px` you mentioned in the issue. To me it looks fine with the original value? 
Screenshot 2023-11-09 191304

**Comment by suchmememanyskill** [comment]
## 80px (original value)
image 

## 50px
image

## SS of deckthemes
bd5c1907-87a4-4eab-8a36-d593dd7a888e

**Comment by AkazaRenn** [comment]
Ok I understand there's a difference, which would be whether the bottom bar overlaps with the container or not. 

It's up to you then, I'm fine with either.

**Pull request merged**
